### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by Amet13** [DeYoungTech/terraform-provider-awslightsail#21]
### Description

Hey.
Great provider, I see that there are some support for container deployment added few days ago.
Is there any plans to release this? Looking forward to use this feature.

**Comment by brittandeyoung** [comment]
@Amet13 Glad to see you are interested in the provider! I am planning on implementing one additional feature yet in this release #19 

I plan on having this feature in and released this week.

**Comment by Amet13** [comment]
Awesome.
Thank you @brittandeyoung

**Comment by brittandeyoung** [comment]
@Amet13 

Release 0.7.0 is live! Please feel free to report any issues you experience.

**Comment by Amet13** [comment]
Just tested it on container service/deployment. Works like a charm!
