### ISSUE TITLE
Bucket Permissions implementation

### ISSUE THREAD

**Issue by aravindakumarbootlabs** [DeYoungTech/terraform-provider-awslightsail#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider has resources to create bucket in lightsail, but no options to configure permissions of the bucket, because of this I cannot attach an instance to the bucket using "Resource Access". Is there any roadmap for these features. I can help implement this.

### New or Affected Resource(s)

* awslightsail_bucket

**Comment by brittandeyoung** [comment]
@aravindakumarbootlabs For transparency, I am now a contributor to the official AWS provider and have added all the functionality of this provider into the official AWS provider. 

I am working on adding this functionality to the main provider now. Part is already merged. 

https://github.com/hashicorp/terraform-provider-aws/pull/28699

**Comment by brittandeyoung** [comment]
@aravindakumarbootlabs All permissions have been added to the official AWS provider.
