### ISSUE TITLE
awslightsail_distribution

### ISSUE THREAD

**Issue by ravibootlabs** [DeYoungTech/terraform-provider-awslightsail#28]
Community Note
Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Description
There is no functionality of creating the distribution in lightsail because of this i can't able to attach my bucket or instance to distribution .Is there any roadmap for these features

New or Affected Resource(s)
awslightsail_distribution

**Comment by brittandeyoung** [comment]
@ravibootlabs I have implemented this on the official AWS provider. This provider is no longer in development and all changes are going into the official aws provider.
